# Site settings
title: tokyoincode
email: kevinmoneil@live.com
description: > # this means to ignore newlines until "baseurl:"
    Web developer in Tokyo.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tokyoincode.github.com" # the base hostname & protocol for your site
twitter_username: tokyoincode
github_username:  tokyoincode

# Build settings
markdown: kramdown
